# Generated by Django 5.0.3 on 2024-03-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_name',
            field=models.CharField(default='Default Location', max_length=255),
        ),
        migrations.AddField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('Other', 'Other'), ('XRLab Blue Cabinet', 'XRLab Blue'), ('XRLab Blue Cabinet Large', 'XRLab Blue Cabinet Large'), ('XRLab Medium Wooden Cabinet', 'XRLab Medium Wooden Cabinet')], default='', max_length=50),
        ),
    ]
