# Generated by Django 5.0.3 on 2024-03-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_location_location_name_location_location_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('PC/Laptop', 'PC/Laptop'), ('Camera/Sensors', 'Camera/Sensors'), ('VR Headset', 'VR Headset'), ('PC Peripherals', 'PC Peripherals'), ('Furniture', 'Furniture'), ('Tripod', 'Tripod'), ('Power/Cable', 'Power/Cable'), ('VR Controller', 'VR Controller'), ('Phones/Tablets', 'Phones/Tablets'), ('Other', 'Other')], max_length=50),
        ),
    ]
