# Generated by Django 5.0.2 on 2024-04-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_equipment_return_date_equipment_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='asset_tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
