# Generated by Django 5.0.2 on 2024-04-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_equipment_asset_tag_alter_equipment_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_name',
            field=models.CharField(blank=True, default='Default Location', max_length=255, null=True),
        ),
    ]
